kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# 1. Control-plane node (Hosts Ingress Controller & handles host port bindings)
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP

# 2. Worker node 1
- role: worker
  

# 3. Worker node 2
- role: worker
